/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    ContactView: typeof import('./src/views/ContactView.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    InnovationView: typeof import('./src/views/InnovationView.vue')['default']
    Inplace: typeof import('./node_modules/primevue/inplace/Inplace.vue')['default']
    InputGroup: typeof import('./node_modules/primevue/inputgroup/InputGroup.vue')['default']
    InputGroupAddon: typeof import('./node_modules/primevue/inputgroupaddon/InputGroupAddon.vue')['default']
    InputIcon: typeof import('./node_modules/primevue/inputicon/InputIcon.vue')['default']
    InputMask: typeof import('./node_modules/primevue/inputmask/InputMask.vue')['default']
    InputNumber: typeof import('./node_modules/primevue/inputnumber/InputNumber.vue')['default']
    InputOtp: typeof import('./node_modules/primevue/inputotp/InputOtp.vue')['default']
    InputSwitch: typeof import('./node_modules/primevue/inputswitch/InputSwitch.vue')['default']
    InputText: typeof import('./node_modules/primevue/inputtext/InputText.vue')['default']
    JumpToPageDropdown: typeof import('./node_modules/primevue/paginator/JumpToPageDropdown.vue')['default']
    JumpToPageInput: typeof import('./node_modules/primevue/paginator/JumpToPageInput.vue')['default']
    Knob: typeof import('./node_modules/primevue/knob/Knob.vue')['default']
    LastPageLink: typeof import('./node_modules/primevue/paginator/LastPageLink.vue')['default']
    Listbox: typeof import('./node_modules/primevue/listbox/Listbox.vue')['default']
    MegaMenu: typeof import('./node_modules/primevue/megamenu/MegaMenu.vue')['default']
    MegaMenuSub: typeof import('./node_modules/primevue/megamenu/MegaMenuSub.vue')['default']
    Menu: typeof import('./node_modules/primevue/menu/Menu.vue')['default']
    Menubar: typeof import('./node_modules/primevue/menubar/Menubar.vue')['default']
    MenubarSub: typeof import('./node_modules/primevue/menubar/MenubarSub.vue')['default']
    Menuitem: typeof import('./node_modules/primevue/menu/Menuitem.vue')['default']
    Message: typeof import('./node_modules/primevue/message/Message.vue')['default']
    MeterGroup: typeof import('./node_modules/primevue/metergroup/MeterGroup.vue')['default']
    MeterGroupLabel: typeof import('./node_modules/primevue/metergroup/MeterGroupLabel.vue')['default']
    Minus: typeof import('./node_modules/primevue/icons/minus/index.vue')['default']
    MultiSelect: typeof import('./node_modules/primevue/multiselect/MultiSelect.vue')['default']
    NewsBoard: typeof import('./src/components/News-Board.vue')['default']
    NewsDetail: typeof import('./src/views/NewsDetail.vue')['default']
    NewsView: typeof import('./src/views/NewsView.vue')['default']
    PageFooter: typeof import('./src/components/Page-Footer.vue')['default']
    PageHeader: typeof import('./src/components/Page-Header.vue')['default']
    ProductionDetail: typeof import('./src/views/ProductionDetail.vue')['default']
    ProductionView: typeof import('./src/views/ProductionView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceView: typeof import('./src/views/ServiceView.vue')['default']
  }
}
