/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    NewsView: typeof import('./src/views/NewsView.vue')['default']
    PageFooter: typeof import('./src/components/Page-Footer.vue')['default']
    PageHeader: typeof import('./src/components/Page-Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
