/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    BreadCrumbs: typeof import('./src/components/BreadCrumbs.vue')['default']
    ContactView: typeof import('./src/views/ContactView.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    InnovationView: typeof import('./src/views/InnovationView.vue')['default']
    NewsBoard: typeof import('./src/components/News-Board.vue')['default']
    NewsDetail: typeof import('./src/views/NewsDetail.vue')['default']
    NewsView: typeof import('./src/views/NewsView.vue')['default']
    PageFooter: typeof import('./src/components/Page-Footer.vue')['default']
    PageHeader: typeof import('./src/components/Page-Header.vue')['default']
    ProductionDetail: typeof import('./src/views/ProductionDetail.vue')['default']
    ProductionView: typeof import('./src/views/ProductionView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceView: typeof import('./src/views/ServiceView.vue')['default']
  }
}
